version: "3.0"

services:
  db:
    image: mysql
    container_name: "fyp_db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./db/init/:/docker-entrypoint-initdb.d/"
      - "dbdata:/var/lib/mysql/"

    environment:
      MYSQL_ROOT_PASSWORD: test

  api:
    container_name: "fyp_api"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./api/app/:/app/"
      - "assets:/assets"
      - "instances:/instances"
    depends_on:
      - training_instance
      - db

  training_instance:
    container_name: "fyp_training_instance"
    build:
      context: ./trainingInstance
      dockerfile: Dockerfile
    volumes:
      - "instances:/app/instances"
      - "assets:/assets"
    ports:
      - "80:80"
    depends_on:
      - db


volumes:
  assets:
  instances:
  dbdata:
