version: "3.0"

services:

  db:
    image: mysql
    container_name: "fyp_db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # build:
    #   context: ./db
    #   dockerfile: Dockerfile
    volumes:
      - "./db/init/:/docker-entrypoint-initdb.d/"
      - "./db/data/:/var/lib/mysql/"

    environment:
      MYSQL_ROOT_PASSWORD: test

  api:
    container_name: "fyp_api"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./api/app/:/app/"
    depends_on:
      - training_instance
      - db

  training_instance:
    container_name: "fyp_training_instance"
    build:
      context: ./trainingInstance
      dockerfile: Dockerfile
    volumes:
      - "./trainingInstance/app/:/app/"
    ports:
      - "80:80"
    depends_on:
      - db
